# Generated by Django 5.1.1 on 2024-09-22 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experiences', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='experience',
            old_name='start_at',
            new_name='start',
        ),
        migrations.AlterField(
            model_name='experience',
            name='city',
            field=models.CharField(default='서울', max_length=80),
        ),
        migrations.AlterField(
            model_name='experience',
            name='country',
            field=models.CharField(default='한국', max_length=50),
        ),
        migrations.AlterField(
            model_name='experience',
            name='price',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='perk',
            name='details',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='perk',
            name='explanation',
            field=models.TextField(blank=True, default=''),
        ),
    ]
